/**
 * Artifact Viewer Component
 * Displays structured artifacts (PRD, Architecture, Code, etc.) generated by agents
 */

import React from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@shared/ui/card';
import { Button } from '@shared/ui/button';
import { Badge } from '@shared/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@shared/ui/tabs';
import {
  FileText,
  Code,
  TestTube,
  Rocket,
  Palette,
  FileCode,
  Download,
  Copy,
  Check,
  ExternalLink,
} from 'lucide-react';
import { cn } from '@shared/lib/utils';
import { Artifact, ArtifactType } from '@core/ai/orchestration/workflow-orchestration';
import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';

interface ArtifactViewerProps {
  artifact: Artifact;
  onClose?: () => void;
  className?: string;
}

const ArtifactIcons: Record<ArtifactType, React.ComponentType<{ className?: string }>> = {
  prd: FileText,
  architecture: Code,
  design: Palette,
  code: FileCode,
  tests: TestTube,
  documentation: FileText,
  deployment: Rocket,
  report: FileText,
};

const ArtifactColors: Record<ArtifactType, string> = {
  prd: 'from-blue-500 to-cyan-500',
  architecture: 'from-purple-500 to-pink-500',
  design: 'from-pink-500 to-rose-500',
  code: 'from-green-500 to-emerald-500',
  tests: 'from-yellow-500 to-orange-500',
  documentation: 'from-indigo-500 to-blue-500',
  deployment: 'from-red-500 to-orange-500',
  report: 'from-slate-500 to-gray-500',
};

export const ArtifactViewer: React.FC<ArtifactViewerProps> = ({
  artifact,
  onClose,
  className,
}) => {
  const [isCopied, setIsCopied] = React.useState(false);
  const ArtifactIcon = ArtifactIcons[artifact.type];
  const gradientColor = ArtifactColors[artifact.type];

  const handleCopy = async () => {
    await navigator.clipboard.writeText(artifact.content);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([artifact.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${artifact.title.replace(/\s+/g, '-').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getStatusColor = (status: Artifact['metadata']['status']) => {
    switch (status) {
      case 'approved':
        return 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400';
      case 'review':
        return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400';
      case 'rejected':
        return 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400';
      default:
        return 'bg-slate-100 text-slate-800 dark:bg-slate-900/30 dark:text-slate-400';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      className={cn('w-full h-full', className)}
    >
      <Card className="border-border bg-card h-full flex flex-col">
        <CardHeader>
          {/* Header */}
          <div className="flex items-start justify-between">
            <div className="flex items-start space-x-4">
              <div
                className={cn(
                  'flex h-12 w-12 items-center justify-center rounded-lg bg-gradient-to-br',
                  gradientColor
                )}
              >
                <ArtifactIcon className="h-6 w-6 text-white" />
              </div>
              <div>
                <CardTitle className="text-xl">{artifact.title}</CardTitle>
                <div className="mt-1 flex items-center space-x-2">
                  <Badge variant="outline" className="text-xs">
                    {artifact.type}
                  </Badge>
                  <Badge className={getStatusColor(artifact.metadata.status)}>
                    {artifact.metadata.status}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    v{artifact.metadata.version}
                  </span>
                </div>
                <div className="mt-2 text-sm text-muted-foreground">
                  Created by {artifact.agentName} •{' '}
                  {artifact.metadata.createdAt.toLocaleString()}
                </div>
              </div>
            </div>

            <div className="flex items-center space-x-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopy}
              >
                {isCopied ? (
                  <Check className="mr-2 h-4 w-4" />
                ) : (
                  <Copy className="mr-2 h-4 w-4" />
                )}
                {isCopied ? 'Copied!' : 'Copy'}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDownload}
              >
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
              {onClose && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onClose}
                >
                  Close
                </Button>
              )}
            </div>
          </div>
        </CardHeader>

        <CardContent className="flex-1 overflow-auto">
          {/* Sections or Full Content */}
          {artifact.sections && Object.keys(artifact.sections).length > 0 ? (
            <Tabs defaultValue={Object.keys(artifact.sections)[0]} className="w-full">
              <TabsList className="w-full justify-start overflow-x-auto">
                {Object.keys(artifact.sections).map((section) => (
                  <TabsTrigger key={section} value={section} className="capitalize">
                    {section.replace(/_/g, ' ')}
                  </TabsTrigger>
                ))}
                <TabsTrigger value="full">Full Document</TabsTrigger>
              </TabsList>

              {Object.entries(artifact.sections).map(([section, content]) => (
                <TabsContent key={section} value={section} className="mt-4">
                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    <h2 className="capitalize">{section.replace(/_/g, ' ')}</h2>
                    <ReactMarkdown
                      components={{
                        code({ node, inline, className, children, ...props }) {
                          const match = /language-(\w+)/.exec(className || '');
                          return !inline && match ? (
                            <SyntaxHighlighter
                              style={vscDarkPlus}
                              language={match[1]}
                              PreTag="div"
                              {...props}
                            >
                              {String(children).replace(/\n$/, '')}
                            </SyntaxHighlighter>
                          ) : (
                            <code className={className} {...props}>
                              {children}
                            </code>
                          );
                        },
                      }}
                    >
                      {content || '*No content yet*'}
                    </ReactMarkdown>
                  </div>
                </TabsContent>
              ))}

              <TabsContent value="full" className="mt-4">
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <ReactMarkdown
                    components={{
                      code({ node, inline, className, children, ...props }) {
                        const match = /language-(\w+)/.exec(className || '');
                        return !inline && match ? (
                          <SyntaxHighlighter
                            style={vscDarkPlus}
                            language={match[1]}
                            PreTag="div"
                            {...props}
                          >
                            {String(children).replace(/\n$/, '')}
                          </SyntaxHighlighter>
                        ) : (
                          <code className={className} {...props}>
                            {children}
                          </code>
                        );
                      },
                    }}
                  >
                    {artifact.content}
                  </ReactMarkdown>
                </div>
              </TabsContent>
            </Tabs>
          ) : (
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown
                components={{
                  code({ node, inline, className, children, ...props }) {
                    const match = /language-(\w+)/.exec(className || '');
                    return !inline && match ? (
                      <SyntaxHighlighter
                        style={vscDarkPlus}
                        language={match[1]}
                        PreTag="div"
                        {...props}
                      >
                        {String(children).replace(/\n$/, '')}
                      </SyntaxHighlighter>
                    ) : (
                      <code className={className} {...props}>
                        {children}
                      </code>
                    );
                  },
                }}
              >
                {artifact.content}
              </ReactMarkdown>
            </div>
          )}

          {/* Dependencies */}
          {artifact.metadata.dependencies.length > 0 && (
            <div className="mt-6 pt-6 border-t border-border">
              <h3 className="text-sm font-semibold mb-3">Dependencies</h3>
              <div className="space-y-2">
                {artifact.metadata.dependencies.map((depId) => (
                  <div
                    key={depId}
                    className="flex items-center space-x-2 text-sm text-muted-foreground"
                  >
                    <ExternalLink className="h-3 w-3" />
                    <span>{depId}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Metadata */}
          <div className="mt-6 pt-6 border-t border-border">
            <h3 className="text-sm font-semibold mb-3">Metadata</h3>
            <dl className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <dt className="text-muted-foreground">Created</dt>
                <dd className="font-medium">
                  {artifact.metadata.createdAt.toLocaleString()}
                </dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Updated</dt>
                <dd className="font-medium">
                  {artifact.metadata.updatedAt.toLocaleString()}
                </dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Version</dt>
                <dd className="font-medium">v{artifact.metadata.version}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Status</dt>
                <dd>
                  <Badge className={getStatusColor(artifact.metadata.status)}>
                    {artifact.metadata.status}
                  </Badge>
                </dd>
              </div>
              <div className="col-span-2">
                <dt className="text-muted-foreground">Author</dt>
                <dd className="font-medium">
                  {artifact.agentName} ({artifact.agentId})
                </dd>
              </div>
            </dl>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
};

export default ArtifactViewer;
