/**
 * Generated Video Preview Component
 * Displays videos generated by Google Veo with download and playback controls
 */

import React, { useState, useRef } from 'react';
import { Download, Maximize2, X, Play, Pause, Volume2, VolumeX, Loader2 } from 'lucide-react';
import { Button } from '@shared/ui/button';
import { Card, CardContent } from '@shared/ui/card';
import { Progress } from '@shared/ui/progress';
import { Slider } from '@shared/ui/slider';
import { cn } from '@shared/lib/utils';
import { googleVeoService } from '@core/integrations/google-veo-service';

export interface GeneratedVideoPreviewProps {
  videoUrl: string;
  thumbnailUrl?: string;
  prompt: string;
  model?: string;
  metadata?: {
    resolution?: string;
    duration?: number;
    fps?: number;
    aspectRatio?: string;
    hasAudio?: boolean;
  };
  isGenerating?: boolean;
  progress?: number;
  className?: string;
  onDownload?: () => void;
}

export const GeneratedVideoPreview: React.FC<GeneratedVideoPreviewProps> = ({
  videoUrl,
  thumbnailUrl,
  prompt,
  model,
  metadata,
  isGenerating = false,
  progress = 0,
  className,
  onDownload,
}) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [volume, setVolume] = useState(100);

  const handlePlayPause = () => {
    if (videoRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
      } else {
        videoRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  const handleMuteToggle = () => {
    if (videoRef.current) {
      videoRef.current.muted = !isMuted;
      setIsMuted(!isMuted);
    }
  };

  const handleVolumeChange = (value: number[]) => {
    const newVolume = value[0];
    setVolume(newVolume);
    if (videoRef.current) {
      videoRef.current.volume = newVolume / 100;
      if (newVolume === 0) {
        setIsMuted(true);
      } else if (isMuted) {
        setIsMuted(false);
      }
    }
  };

  const handleTimeUpdate = () => {
    if (videoRef.current) {
      setCurrentTime(videoRef.current.currentTime);
    }
  };

  const handleLoadedMetadata = () => {
    if (videoRef.current) {
      setDuration(videoRef.current.duration);
    }
  };

  const handleSeek = (value: number[]) => {
    const time = value[0];
    if (videoRef.current) {
      videoRef.current.currentTime = time;
      setCurrentTime(time);
    }
  };

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const filename = `veo-${Date.now()}.mp4`;
      await googleVeoService.downloadVideo(videoUrl, filename);
      onDownload?.();
    } catch (error) {
      console.error('Failed to download video:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  const handleFullscreen = () => {
    setIsFullscreen(true);
  };

  const handleCloseFullscreen = () => {
    setIsFullscreen(false);
    if (videoRef.current) {
      videoRef.current.pause();
      setIsPlaying(false);
    }
  };

  const formatTime = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  if (isGenerating) {
    return (
      <Card className={cn('overflow-hidden', className)}>
        <CardContent className="p-6">
          <div className="flex flex-col items-center justify-center space-y-4">
            <Loader2 className="h-12 w-12 animate-spin text-indigo-600" />
            <div className="w-full space-y-2">
              <div className="flex justify-between text-sm text-gray-600 dark:text-gray-400">
                <span>Generating video...</span>
                <span>{Math.floor(progress)}%</span>
              </div>
              <Progress value={progress} className="h-2" />
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400 text-center line-clamp-2">
              {prompt}
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card className={cn('overflow-hidden', className)}>
        <CardContent className="p-0">
          <div className="relative group">
            {/* Video Player */}
            <div className="relative bg-black">
              <video
                ref={videoRef}
                src={videoUrl}
                poster={thumbnailUrl}
                className="w-full h-auto"
                onTimeUpdate={handleTimeUpdate}
                onLoadedMetadata={handleLoadedMetadata}
                onEnded={() => setIsPlaying(false)}
                loop
              >
                Your browser does not support the video tag.
              </video>

              {/* Play/Pause Overlay */}
              {!isPlaying && (
                <div
                  className="absolute inset-0 flex items-center justify-center cursor-pointer bg-black/20 hover:bg-black/30 transition-colors"
                  onClick={handlePlayPause}
                >
                  <div className="w-16 h-16 bg-white/90 rounded-full flex items-center justify-center shadow-lg">
                    <Play className="h-8 w-8 text-gray-900 ml-1" />
                  </div>
                </div>
              )}

              {/* Controls Overlay */}
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                {/* Progress Bar */}
                <Slider
                  value={[currentTime]}
                  max={duration || 100}
                  step={0.1}
                  onValueChange={handleSeek}
                  className="mb-2"
                />

                <div className="flex items-center justify-between">
                  {/* Left Controls */}
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={handlePlayPause}
                      className="text-white hover:bg-white/10"
                    >
                      {isPlaying ? (
                        <Pause className="h-4 w-4" />
                      ) : (
                        <Play className="h-4 w-4" />
                      )}
                    </Button>

                    {metadata?.hasAudio && (
                      <div className="flex items-center gap-2">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={handleMuteToggle}
                          className="text-white hover:bg-white/10"
                        >
                          {isMuted || volume === 0 ? (
                            <VolumeX className="h-4 w-4" />
                          ) : (
                            <Volume2 className="h-4 w-4" />
                          )}
                        </Button>
                        <Slider
                          value={[volume]}
                          max={100}
                          step={1}
                          onValueChange={handleVolumeChange}
                          className="w-20"
                        />
                      </div>
                    )}

                    <span className="text-white text-sm ml-2">
                      {formatTime(currentTime)} / {formatTime(duration)}
                    </span>
                  </div>

                  {/* Right Controls */}
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={handleFullscreen}
                      className="text-white hover:bg-white/10"
                    >
                      <Maximize2 className="h-4 w-4" />
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={handleDownload}
                      disabled={isDownloading}
                      className="text-white hover:bg-white/10"
                    >
                      {isDownloading ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Download className="h-4 w-4" />
                      )}
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Metadata */}
          <div className="p-3 bg-gray-50 dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800">
            <p className="text-sm text-gray-600 dark:text-gray-400 line-clamp-2">
              {prompt}
            </p>
            {(model || metadata) && (
              <div className="flex flex-wrap gap-2 mt-2 text-xs text-gray-500 dark:text-gray-500">
                {model && (
                  <span className="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">
                    {model}
                  </span>
                )}
                {metadata?.resolution && (
                  <span className="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">
                    {metadata.resolution}
                  </span>
                )}
                {metadata?.duration && (
                  <span className="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">
                    {metadata.duration}s
                  </span>
                )}
                {metadata?.fps && (
                  <span className="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">
                    {metadata.fps} FPS
                  </span>
                )}
                {metadata?.hasAudio && (
                  <span className="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">
                    Audio
                  </span>
                )}
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Fullscreen Modal */}
      {isFullscreen && (
        <div
          className="fixed inset-0 z-50 bg-black flex items-center justify-center"
          onClick={handleCloseFullscreen}
        >
          <Button
            size="sm"
            variant="ghost"
            onClick={handleCloseFullscreen}
            className="absolute top-4 right-4 text-white hover:bg-white/10"
          >
            <X className="h-6 w-6" />
          </Button>
          <video
            src={videoUrl}
            controls
            autoPlay
            className="max-w-full max-h-full"
            onClick={(e) => e.stopPropagation()}
          >
            Your browser does not support the video tag.
          </video>
        </div>
      )}
    </>
  );
};
